### ISSUE TITLE
Shadows (Post Processing)

### ISSUE THREAD

**Issue by Armintron** [ctcuff/stargazers#14]
## shadows
- [x] Create shadow map
- [x] Apply shadow map
- [x] Create debug call to render the map
- [x] Blur map to make resulting shadows smoother

## post processing
- [x] Create Post-processing pipeline
- [x] Pull bright info from scene 
- [x] Apply blurred bloom to scene

**Comment by TheIceCreamBear** [comment]
Unlinked Post processing (#30) due to update in issue comment
